title:        {"SMS"}
url:          http://sms.apievangelist.com
version:      1.1.1
author:
  name:       'Kin Lane'
  sms:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/news/page:num"

production_url : http://sms.apievangelist.com

BASE_PATH : http://sms.apievangelist.com

categories_path : /categories.html
tags_path : /tags.html

oauthio : I_TRiPFUBHSp-3DxS5RjS9ub8sg
org : kinlane
repo : sms