title:        SMS APIs
url:          http://sms.stack.network
logo:         https://s3.amazonaws.com/kinlane-productions/api-stack/logos/api-stack-sms.png
logo_width:   65
logo_bottom_padding: 0

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 500
paginate_path: "/news/page:num/"

categories_path : /categories.html
tags_path : /tags.html

github_user: api-stack
github_repo: sms

# Masthead title
masthead_link: http://sms.stack.network
masthead_font_size: 75
masthead_title: '{"SMS APIs"}'

# Feature
feature_title: API Guide
feature_link: http://apievangelist.com
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/api-guides-loading.jpg
feature_image_width: 50

# Project
project_image: https://s3.amazonaws.com/kinlane-productions/api-stack/icons/bw-sms.png
project_summary: Research into SMS APIs, trying to profile each provider, as well as the common building blocks, plans, and other elements of how they are operating their APIs.

# Navigation
navigation:
  - label1: Home
    link1: /index.html
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 0
    decorate: 0
  - label1: News
    link1: /news/
    size1: 80
    extend: 1
    label2: RSS
    link2: /blog.xml
    size2: 60
    padding: 2
    decorate: 0
  - label1: APIs
    link1: /apis/
    size1: 80
    extend: 1
    label2: JSON
    link2: /apis.json
    size2: 60
    padding: 0
    decorate: 0
  - label1: Plans
    link1: /plans/
    size1: 80
    extend: 0
    label2: JSON
    link2: /data/organizations.json
    size2: 60
    padding: 0
    decorate: 0
  - label1: Return to API Evangelist
    link1: http://apievangelist.com
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 10
    padding: 20
    decorate: 1

# Footer Navigation
footernavigation:
  - label: API 100K View
    link: http://apievangelist.com
  - label: News
    link: /news/
  - label: Partners
    link: http://apievangelist.com/partners/
  - label: APIs.json
    link: http://apisjson.org
  - label: About Kin Lane
    link: http://kinlane.com
  - label: Branding Guidelines
    link: http://apievangelist.com/branding-guidelines.html
  - label: Contact
    link: http://kinlane.com/contacts/

# sponsors
sponsors_margin_top: 3
sponsors_padding_top: 3
sponsors_json_url: https://s3.amazonaws.com/kinlane-productions/json/sponsors.json

# support
support_title: Support My SMS API Reshipping
support_header: I depend on the support of my partners to fund my work as an independent analysts. I have been monitoring the world of APIs since July of 2010 through the support of my partners, and a handful of writing or consulting projects along the way. If you find what I do valuable, please help support me by purchasing my guides, giving below, or if there are specific aspects of SMS APIs you'd like me to focus on, let me know, and maybe we can find a way to provide you with what you are looking for.
support_footer: I pay my bills by consulting on API projects, and writing white papers and guides. You can find much of my reSMS freely available across my website(s). Let me know how I can make my search API research more valuable to you. Thank you for your support, and feel free to ping me directly if you have more questions.
